<div class="left">
    <div class="phone">
        <em class="las la-phone"></em>
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('phone-top-header')
            ->toHtml();
        ?>
    </div>

    <div class="email">
        <em class="las la-envelope"></em>
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('email-top-header')
            ->toHtml();
        ?>
    </div>
</div>
