<div class="section-navigation-box">
    <div class="nav-left">
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('nav-left')
            ->toHtml();
        ?>
    </div>

    <div class="nav-center">
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('nav-center')
            ->toHtml();
        ?>
    </div>

    <div class="nav-right">
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('nav-right')
            ->toHtml();
        ?>
    </div>
</div>

<div class="section-navigation-mobile">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('nav-mobile')
        ->toHtml();
    ?>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $('.section-navigation-mobile').find('p').find('em.la-bars').on('click', function() {
                $('.section-nav-responsive').addClass('toShow');
            });

            $('.section-navigation-responsive').find('em.la-times').on('click', function() {
                $('.section-nav-responsive').removeClass('toShow');
            });
        });
    });
</script>
