<div class="footer-bottom-box">
    <div class="footer-bottom-copyright">
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-copyright')
            ->toHtml();
        ?>
    </div>

    <div class="footer-bottom-menu">
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-menu')
            ->toHtml();
        ?>
    </div>
</div>
